#!/bin/sh
cd
cd naccess2.1.1
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb154l.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1aaz.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1acx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1add.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ade.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ahb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1alk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1amg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1amp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1aor.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1aoz.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1asw.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1atp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1avh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1aya.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1azu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bam.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bbp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bcx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bdo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bds.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bet.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bfg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bmv.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bnc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bov.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bph.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1brs.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1bsd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cbg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cbh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cc5.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cdl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cdt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cei.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cel.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cem.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ceo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cew.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cfb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cfr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cgu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1chb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1chd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1chk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1chm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cks.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1clc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cns.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1coi.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1col.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1com.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cpc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cpn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cqa.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1crn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cse.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1csm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ctf.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cth.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ctm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ctn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ctu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cxs.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1cyx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1daa.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dar.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1del.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dfj.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dfn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dih.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dik.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1din.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dkz.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dlc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dnp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dpg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dsb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dts.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dup.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1dyn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1eca.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ece.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ecl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ecp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1edd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1edm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1edn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1eft.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1efu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1epb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ese.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1esl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1etu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1euu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fba.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fbl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fc2.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fdl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fdt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fdx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fin.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fjm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fkf.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fnd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fua.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fuq.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1fxi.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gal.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gcb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gcm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gd1.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gdj.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gep.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gfl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ghs.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gky.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gln.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gmp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gnd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gog.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gp1.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gp2.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gpc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gpm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1grj.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gtm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gtq.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1gym.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1han.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hcg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hcr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hip.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hiw.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hjr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hmp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hmy.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hnf.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hor.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hpl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hsl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1htr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hup.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hvq.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hxn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1hyp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ign.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1il8.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ilk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1inp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1irk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1isa.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1isu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1jud.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1kin.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1knb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1kpt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1krc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1kte.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ktq.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1kuh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1l58.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lap.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lat.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lba.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lbu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1leh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lib.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lis.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lki.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lmb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lpb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1lpe.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mai.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mas.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mct.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mda.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mdt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mjc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mla.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mmo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mns.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mof.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mrr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1mrt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1msp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nal.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nar.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nba.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ncg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ndh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nfp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nga.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nlk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nol.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1nox.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1noz.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1oac.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1onr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1otg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ovb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ovo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1oxy.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1oyc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1paz.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pbp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pbw.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pda.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pdn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pdo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pga.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pht.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pii.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pky.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pmi.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pnm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pnt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1poc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pow.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ppi.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ppt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ptr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ptx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pyp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1pyt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1qbb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1qrd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1r09.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rbp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rec.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1reg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1req.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rhd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rhg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rie.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ris.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rld.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rlr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rpo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rsy.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1rvv.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1s01.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1scu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1sei.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ses.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1sfe.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1sft.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1sh1.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1smn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1smp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1spb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1sra.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1srj.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1stf.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1stm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1svb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tab.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1taq.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tcb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tcr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tfr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tht.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1thx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tie.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tif.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tig.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tii.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tml.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tnd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tnf.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tpl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1trb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1trh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1trk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tsp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tss.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tul.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1tup.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ubd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ubq.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1udh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1umu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vca.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vcc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vhh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vhr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vid.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vjs.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vmo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vnc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vok.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1vpt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1wap.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1wfb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1whi.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1wsy.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1xva.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1ypt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1yrn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1znb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb1zym.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb256b.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2aai.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2aat.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2abk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2adm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2afn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2ak3.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2alp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2asr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2bat.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2blt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2bop.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2cab.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2ccy.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2cmd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2cpo.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2cyp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2dkb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2dln.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2dnj.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2ebn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2end.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2erl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2fox.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2fxb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2gbp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2gcr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2gls.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2gn5.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2gsq.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2hft.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2hhm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2hip.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2hmz.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2hpr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2i1b.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2ltn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2mev.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2mhu.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2mlt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2mta.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2nad.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2npx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2olb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2or1.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2pab.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2pgd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2phh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2phy.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2pol.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2reb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2rsl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2rsp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2scp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2sil.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2sns.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2sod.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2spt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2stv.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2tgi.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2tgp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2tmd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2tmv.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2trt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2tsc.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2utg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2wrp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb2yhx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3ait.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3b5c.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3bcl.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3blm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3cd4.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3chy.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3cla.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3cln.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3cox.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3eca.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3gap.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3hmg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3icb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3ink.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3mdd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3pgk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3pgm.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3pmg.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3rnt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb3tim.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4bp2.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4cpa.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4fis.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4gr1.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4pfk.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4rhv.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4rxn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4sdh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4sgb.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4ts1.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb4xia.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb5cyt.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb5er2.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb5ldh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb5lyz.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb5sic.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6acn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6cpa.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6cpp.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6cts.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6dfr.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6hir.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6rlx.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb6tmn.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb7cat.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb7icd.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb7rsa.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb821p.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb8adh.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb9api.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb9ins.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb9pap.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb9wga.ent
alias naccess="/home/ypfeng/04spring_resol_smallerthan2A/pdb_calc/naccess"
naccess pdb9wga.ent
